### ISSUE TITLE
Reformat scripts to conform with PEP8 style

### ISSUE THREAD

**Issue by jaredalee** [NCAR/wps_wrf_workflow#10]
## Describe the Task ##
Use PyCharm to help reformat all scripts in this repo to use PEP8 style.

### Time Estimate ###
1–2 hours

### Relevant Deadlines ###
NONE

### New Parameters ###
NONE

### Technical References ###
[PEP8 Style Guide](https://peps.python.org/pep-0008/)
[PyCharm guide](https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html)

### Funding Source ###
Multiscale Workflow project

### Assignee ###
- [x] Assign this Task to the appropriate person

### Labels ###
- [ ] Select **component**
- [x] Select **priority**
- [x] Select **requestor(s)**

## Task Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
